# 切到 repo
cd /path/to/spiritual-health-assessment   # 改成你本機路徑，或在 Trae terminal 已在 repo 根目錄就不用改

# 從 main 建新的測試 branch
git checkout main
git pull origin main
git checkout -b fix/deploy-workflow

# 建目錄（若已存在會跳過）
mkdir -p .github/workflows

# 用你的編輯器把畫布內容貼進這個檔案
# (如果你在終端會用 echo >> 但建議用編輯器貼上，下面示範用 nano)
nano .github/workflows/deploy.yml
# (在 nano 裡貼上畫布內容 → Ctrl+O 存檔 → Enter → Ctrl+X 離開)
